# Generated by Django 5.2.4 on 2025-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wafcore', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.UniqueConstraint(fields=('port', 'ip'), name='unique_port_ip'),
        ),
    ]
